version: "3"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ospp-nest
    ports:
      - "3306:3306"
  tiny-nestjs:
    image: node:18
    working_dir: /usr/src/app
    volumes:
      - ./:/app
    command: npm run start
    ports:
      - "3000:3000"
